"""empty message

Revision ID: 072e57d254d7
Revises: a3a5c495457f
Create Date: 2024-08-29 17:48:34.824223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072e57d254d7'
down_revision = 'a3a5c495457f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email_key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('position_key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('department_key', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('employees_email_key', type_='unique')
        batch_op.drop_constraint('employees_position_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('employees_department_id_fkey', type_='foreignkey')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('department_id')
        batch_op.drop_column('email')
        batch_op.drop_column('position_id')

    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_salary_key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('salary_coefficient_key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_salary_key', sa.String(length=50), nullable=True))
        batch_op.drop_column('total_salary')
        batch_op.drop_column('salary_coefficient')
        batch_op.drop_column('basic_salary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('salary_coefficient', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('total_salary_key')
        batch_op.drop_column('salary_coefficient_key')
        batch_op.drop_column('basic_salary_key')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('employees_department_id_fkey', 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key('employees_position_id_fkey', 'positions', ['position_id'], ['id'])
        batch_op.create_unique_constraint('employees_email_key', ['email'])
        batch_op.drop_column('department_key')
        batch_op.drop_column('position_key')
        batch_op.drop_column('email_key')
        batch_op.drop_column('phone_number_key')

    # ### end Alembic commands ###
